=== thoaddinh/Hostel_ASP.NET_XML/VectorHostel_xml/VectorHostel_xml/xml/VectorHostel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLPT">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="phongtro">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:whiteSpace value="preserve"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="4"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tinhtrang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="full|empty"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="mota">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:whiteSpace value="preserve"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="malp">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[LP][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="loaiphong">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="malp">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[LP][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tenlp" type="xs:string"/>
                            <xs:element name="dongia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="phieuthue">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maphieu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ngaythue" type="xs:date"/>
                            <xs:element name="ngaytra" type="xs:date"/>
                            <xs:element name="maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="makh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[K][H][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="khach">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="makh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[K][H][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cmnd">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="hoten">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:whiteSpace value="preserve"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sdt">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{4}[.][0-9]{6}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="diachi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:whiteSpace value="preserve"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="gioitinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="nam|ná»¯"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ngaysinh" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="phieuthanhtoan">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maphieutt">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][T][T][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tiendien" type="xs:double"/>
                            <xs:element name="tiennuoc" type="xs:double"/>
                            <xs:element name="thang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nam">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="2000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="phieuthudien">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maptd">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][T][D][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="chisocu" type="xs:decimal"/>
                            <xs:element name="chisomoi" type="xs:decimal"/>
                            <xs:element name="thang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nam">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:pattern value="[\-+]?[0-9]+"/>
                                        <xs:minInclusive value="2000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="5" name="phieuthunuoc">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="maptn">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][T][N][0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="maphong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[P][0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="chisocu" type="xs:decimal"/>
                            <xs:element name="chisomoi" type="xs:decimal"/>
                            <xs:element name="thang">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nam">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="2000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="ID_phongtro">
            <xs:selector xpath="phongtro"/>
            <xs:field xpath="maphong"/>
        </xs:key>
        <xs:key name="ID_loaiphong">
            <xs:selector xpath="loaiphong"/>
            <xs:field xpath="malp"/>
        </xs:key>
        <xs:key name="ID_phieuthue">
            <xs:selector xpath="phieuthue"/>
            <xs:field xpath="maphieu"/>
        </xs:key>
        <xs:key name="ID_khach">
            <xs:selector xpath="khach"/>
            <xs:field xpath="makh"/>
        </xs:key>
        <xs:key name="ID_phieuTT">
            <xs:selector xpath="phieuthanhtoan"/>
            <xs:field xpath="maphieutt"/>
        </xs:key>
        <xs:key name="ID_phieudien">
            <xs:selector xpath="phieuthudien"/>
            <xs:field xpath="maptd"/>
        </xs:key>
        <xs:key name="ID_phieunuoc">
            <xs:selector xpath="phieuthunuoc"/>
            <xs:field xpath="maptn"/>
        </xs:key>
        <xs:keyref name="IDREF_phong_lp" refer="ID_loaiphong">
            <xs:selector xpath="phongtro"/>
            <xs:field xpath="malp"/>
        </xs:keyref>
        <xs:keyref name="IDREF_phieuthue_phong" refer="ID_phongtro">
            <xs:selector xpath="phieuthue"/>
            <xs:field xpath="maphong"/>
        </xs:keyref>
        <xs:keyref name="IDREF_phieuthue_khach" refer="ID_khach">
            <xs:selector xpath="phieuthue"/>
            <xs:field xpath="makh"/>
        </xs:keyref>
        <xs:keyref name="IDREF_ptt_phong" refer="ID_phongtro">
            <xs:selector xpath="phieuthanhtoan"/>
            <xs:field xpath="maphong"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== thoaddinh/Hostel_ASP.NET_XML/VectorHostel_xml/VectorHostel_xml/xml/VectorHostel1.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLPT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="VectorHostel.xsd">
  <phongtro>
    <maphong>P001</maphong>
    <tenphong>tenphong0</tenphong>
    <tang>2</tang>
    <tinhtrang>full</tinhtrang>
    <mota>mota0</mota>
    <malp>L01</malp>
  </phongtro>
  <phongtro>
    <maphong>P002</maphong>
    <tenphong>tenphong1</tenphong>
    <tang>2</tang>
    <tinhtrang>empty</tinhtrang>
    <mota>mota1</mota>
    <malp>L02</malp>
  </phongtro>
  <phongtro>
    <maphong>P003</maphong>
    <tenphong>tenphong2</tenphong>
    <tang>2</tang>
    <tinhtrang>full</tinhtrang>
    <mota>mota2</mota>
    <malp>L03</malp>
  </phongtro>
  <phongtro>
    <maphong>P004</maphong>
    <tenphong>tenphong3</tenphong>
    <tang>2</tang>
    <tinhtrang>empty</tinhtrang>
    <mota>mota3</mota>
    <malp>L04</malp>
  </phongtro>
  <phongtro>
    <maphong>P005</maphong>
    <tenphong>tenphong4</tenphong>
    <tang>2</tang>
    <tinhtrang>empty</tinhtrang>
    <mota>mota4</mota>
    <malp>L05</malp>
  </phongtro>
  <loaiphong>
    <malp>L01</malp>
    <tenlp>tenlp0</tenlp>
    <dongia>200</dongia>
  </loaiphong>
  <loaiphong>
    <malp>L02</malp>
    <tenlp>tenlp1</tenlp>
    <dongia>250</dongia>
  </loaiphong>
  <loaiphong>
    <malp>L03</malp>
    <tenlp>tenlp2</tenlp>
    <dongia>300</dongia>
  </loaiphong>
  <loaiphong>
    <malp>L05</malp>
    <tenlp>tenlp3</tenlp>
    <dongia>300</dongia>
  </loaiphong>
  <loaiphong>
    <malp>L04</malp>
    <tenlp>tenlp4</tenlp>
    <dongia>350</dongia>
  </loaiphong>
  <phieuthue>
    <maphieu>P01</maphieu>
    <ngaythue>2019-05-20</ngaythue>
    <ngaytra>2019-05-22</ngaytra>
    <maphong>P001</maphong>
    <makh>KH01</makh>
  </phieuthue>
  <phieuthue>
    <maphieu>P02</maphieu>
    <ngaythue>2019-05-10</ngaythue>
    <ngaytra>2019-05-11</ngaytra>
    <maphong>P002</maphong>
    <makh>KH02</makh>
  </phieuthue>
  <phieuthue>
    <maphieu>P03</maphieu>
    <ngaythue>2019-04-15</ngaythue>
    <ngaytra>2006-04-19</ngaytra>
    <maphong>P004</maphong>
    <makh>KH03</makh>
  </phieuthue>
  <phieuthue>
    <maphieu>P04</maphieu>
    <ngaythue>2019-05-04</ngaythue>
    <ngaytra>2019-05-06</ngaytra>
    <maphong>P005</maphong>
    <makh>KH04</makh>
  </phieuthue>
  <phieuthue>
    <maphieu>P05</maphieu>
    <ngaythue>2019-03-10</ngaythue>
    <ngaytra>2019-03-13</ngaytra>
    <maphong>P003</maphong>
    <makh>KH05</makh>
  </phieuthue>
  <khach>
    <makh>KH01</makh>
    <cmnd>657588993</cmnd>
    <hoten>Lê Thị Mai</hoten>
    <sdt>0986.543393</sdt>
    <diachi>Nha Trang</diachi>
    <gioitinh>nữ</gioitinh>
    <ngaysinh>1992-05-04</ngaysinh>
  </khach>
  <khach>
    <makh>KH02</makh>
    <cmnd>567389204</cmnd>
    <hoten>Ma Cao Đào</hoten>
    <sdt>0985.068493</sdt>
    <diachi>Vạn Giã</diachi>
    <gioitinh>nữ</gioitinh>
    <ngaysinh>1997-05-12</ngaysinh>
  </khach>
  <khach>
    <makh>KH03</makh>
    <cmnd>789955467</cmnd>
    <hoten>Liễu Mộng Hoa</hoten>
    <sdt>0765.064858</sdt>
    <diachi>Nha Trang</diachi>
    <gioitinh>nam</gioitinh>
    <ngaysinh>1987-08-02</ngaysinh>
  </khach>
  <khach>
    <makh>KH04</makh>
    <cmnd>846589395</cmnd>
    <hoten>Trần Lanh</hoten>
    <sdt>0124.658394</sdt>
    <diachi>Phú Yên</diachi>
    <gioitinh>nam</gioitinh>
    <ngaysinh>1991-03-04</ngaysinh>
  </khach>
  <khach>
    <makh>KH05</makh>
    <cmnd>546748595</cmnd>
    <hoten>hoten4</hoten>
    <sdt>0674.785467</sdt>
    <diachi>Hà Nội</diachi>
    <gioitinh>nữ</gioitinh>
    <ngaysinh>1899-01-01</ngaysinh>
  </khach>
  <phieuthanhtoan>
    <maphieutt>PTT01</maphieutt>
    <maphong>P001</maphong>
    <tiendien>100000</tiendien>
    <tiennuoc>180600</tiennuoc>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthanhtoan>
    <maphieutt>PTT02</maphieutt>
    <maphong>P002</maphong>
    <tiendien>200000</tiendien>
    <tiennuoc>270600</tiennuoc>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthanhtoan>
    <maphieutt>PTT03</maphieutt>
    <maphong>P003</maphong>
    <tiendien>200</tiendien>
    <tiennuoc>200</tiennuoc>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthanhtoan>
    <maphieutt>PTT04</maphieutt>
    <maphong>P004</maphong>
    <tiendien>200500</tiendien>
    <tiennuoc>180600</tiennuoc>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthanhtoan>
    <maphieutt>PTT05</maphieutt>
    <maphong>P005</maphong>
    <tiendien>202000</tiendien>
    <tiennuoc>202320</tiennuoc>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthanhtoan>
    <maphieutt>PTT06</maphieutt>
    <maphong>P005</maphong>
    <tiendien>50000</tiendien>
    <tiennuoc>200</tiennuoc>
    <thang>10</thang>
    <nam>2019</nam>
  </phieuthanhtoan>
  <phieuthudien>
    <maptd>PTD01</maptd>
    <maphong>P001</maphong>
    <chisocu>60</chisocu>
    <chisomoi>40</chisomoi>
    <thang>10</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD02</maptd>
    <maphong>P002</maphong>
    <chisocu>80</chisocu>
    <chisomoi>111</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD03</maptd>
    <maphong>P003</maphong>
    <chisocu>50</chisocu>
    <chisomoi>90</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD04</maptd>
    <maphong>P004</maphong>
    <chisocu>50</chisocu>
    <chisomoi>68</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD06</maptd>
    <maphong>P005</maphong>
    <chisocu>89</chisocu>
    <chisomoi>100</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD07</maptd>
    <maphong>P005</maphong>
    <chisocu>100</chisocu>
    <chisomoi>112</chisomoi>
    <thang>12</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthudien>
    <maptd>PTD08</maptd>
    <maphong>P001</maphong>
    <chisocu>40</chisocu>
    <chisomoi>60</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthudien>
  <phieuthunuoc>
    <maptn>PTN02</maptn>
    <maphong>P002</maphong>
    <chisocu>44.2</chisocu>
    <chisomoi>134</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN03</maptn>
    <maphong>P003</maphong>
    <chisocu>45</chisocu>
    <chisomoi>112.5</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN04</maptn>
    <maphong>P004</maphong>
    <chisocu>112.5</chisocu>
    <chisomoi>120</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN05</maptn>
    <maphong>P005</maphong>
    <chisocu>112</chisocu>
    <chisomoi>125</chisomoi>
    <thang>11</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN06</maptn>
    <maphong>P005</maphong>
    <chisocu>100</chisocu>
    <chisomoi>112</chisomoi>
    <thang>10</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN07</maptn>
    <maphong>P005</maphong>
    <chisocu>125</chisocu>
    <chisomoi>130</chisomoi>
    <thang>12</thang>
    <nam>2019</nam>
  </phieuthunuoc>
  <phieuthunuoc>
    <maptn>PTN08</maptn>
    <maphong>P001</maphong>
    <chisocu>0</chisocu>
    <chisomoi>22</chisomoi>
    <thang>10</thang>
    <nam>2019</nam>
  </phieuthunuoc>
</QLPT>
